module.exports.secret = 'secret'
module.exports.MONGODB_URI = ''
module.exports.MG_API_KEY = ''
module.exports.DOMAIN = 'https://tasks.com'
module.exports.SG_API_KEY = ''
module.exports.ADMIN_MAIL = 'admin@tasks.com'
